blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/wuhang2014/llm-service/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issues
    url: https://github.com/wuhang2014/llm-service/security/advisories/new
    about: Please report security vulnerabilities privately
