name: Auto-assign reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    
    steps:
    - name: Auto-assign reviewers
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        configuration-path: '.github/auto-assign.yml'
