name: Label PRs

on:
  # Use pull_request_target so the workflow runs with base repo permissions on forked PRs
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    # Optional: checkout base repo (not strictly required by labeler)
    - name: Check out base repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Apply labels
      uses: actions/labeler@v5
      with:
        configuration-path: '.github/labeler.yml'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: false
        dot: true
